name: gomteshupadhye
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8ed'
    - '#121317'
    - '#c5c7d3'
    - '#8b8e9d'
    - '#585c68'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
