name: gomteshupadhye
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6899990430101752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b3b2af'
    - '#f0f1f3'
    - '#f8c300'
    - '#e80034'
  brandStrength: 0.7020541590172797
  lightness: 0.00034323614090681076
  saturation: 0.24569881171919405
  rhythmicContrast: 1
purpose: []
