name: gomteshupadhye
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#010101'
    - '#35363b'
    - '#d66f2c'
    - '#696971'
  brandStrength: 0
  lightness: 0.00034323614090681076
  saturation: 0
  rhythmicContrast: 0
purpose: []
