name: gomteshupadhye
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#949398'
    - '#ed5722'
    - '#bf1575'
  brandStrength: 0.25
  lightness: 0.00034323614090681076
  saturation: 0.24569881171919405
  rhythmicContrast: 1
purpose: []
